// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewTask.Core.Data;

#nullable disable

namespace NewTask.Core.Migrations
{
    [DbContext(typeof(InMemDbContext))]
    [Migration("20220408194044_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("NewTask.Core.Models._Nota", b =>
                {
                    b.Property<int>("NotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpusId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentNotaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NotaId");

                    b.HasIndex("OpusId");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("NewTask.Core.Models._Opus", b =>
                {
                    b.Property<int>("OpusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OpusId");

                    b.ToTable("Opera");
                });
#pragma warning restore 612, 618
        }
    }
}
